import type { NextConfig } from "next";

/** Old or mistyped paths that people and other sites still link to → the real page (one hop). */
const LEGACY_REDIRECTS: ReadonlyArray<{ source: string; destination: string }> =
  [
    { source: `/blog`, destination: `/blogs` },
    { source: `/BlogPreview`, destination: `/blogs` },
    { source: `/galeri`, destination: `/gallery` },
    { source: `/ulasan`, destination: `/ulasan-kami` },
    { source: `/contact`, destination: `/kontak-kami` },
    { source: `/kontak`, destination: `/kontak-kami` },
    { source: `/services`, destination: `/harga` },
    { source: `/price-list`, destination: `/harga` },
    { source: `/kelebihan-kami`, destination: `/` },
    // The manifest is now generated by app/manifest.ts.
    { source: `/site.webmanifest`, destination: `/manifest.webmanifest` },
    // `/l/*` used to be a rewrite that served duplicate pages with 200.
    { source: `/l/:path*`, destination: `/:path*` },
  ];

const SECURITY_HEADERS = [
  { key: `X-Content-Type-Options`, value: `nosniff` },
  { key: `Referrer-Policy`, value: `strict-origin-when-cross-origin` },
  {
    key: `Permissions-Policy`,
    value: `camera=(), microphone=(), geolocation=()`,
  },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  trailingSlash: false,

  images: {
    remotePatterns: [{ protocol: `https`, hostname: `images.unsplash.com` }],
    formats: [`image/avif`, `image/webp`],
    minimumCacheTTL: 60 * 60 * 24 * 30,
  },

  experimental: {
    optimizePackageImports: [`lucide-react`],
    optimizeCss: true,
  },

  // Blog content is read from disk at build time.
  outputFileTracingIncludes: {
    "/blogs/[slug]": [`./content/**/*`],
  },

  headers: async () => [{ source: `/:path*`, headers: SECURITY_HEADERS }],

  redirects: async () =>
    LEGACY_REDIRECTS.map((redirect) => ({ ...redirect, permanent: true })),
};

export default nextConfig;
